PizzariaMVCAtivdade/Controllers/PizzaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PizzariaMVCAtivdade.Models;
using PizzariaMVCAtivdade.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PizzariaMVCAtivdade.Controllers
{
    public class PizzaController : Controller
    {
        private PizzariaDbContext _context;

        public PizzaController(PizzariaDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Pizzas);
        }
        public IActionResult Detalhes(int id)
        {
            var result = _context.Pizzas.FirstOrDefault(x => x.Id == id);
            return View(result);
        }
        public IActionResult Criar(int id)
        {
            DadosDropDown();
            return View();
        }

        [HttpPost, ActionName("Criar Pizza")]
        public IActionResult CriarConfirmar(PostPizzaDTO pizzaDto)
        {
            Pizza pizza = new Pizza
            (
                pizzaDto.Nome,
                pizzaDto.FotoURL,
                pizzaDto.Preco,
                pizzaDto.Tamanho
            );
            _context.Add(pizza);
            _context.SaveChanges();

            foreach (var saborId in pizzaDto.Sabores)
            {
                var s = new PizzaSabor(pizza.Id,saborId);
                _context.PizzasSabores.Add(s);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }




        public void DadosDropDown()
        {
            var result = new PostPizzaDropdownDTO()
            {
                Sabores = _context.Sabores.OrderBy(x => x.Nome).ToList(),
                Tamanhos = _context.Tamanhos.OrderBy(x => x.Nome).ToList()
            };
            ViewBag.Sabores = new SelectList(result.Sabores, "Id", "Nome");
            ViewBag.Tamanhos = new SelectList(result.Tamanhos, "Id", "Nome");
        }
    }
}

PizzariaMVCAtivdade/Controllers/SaborController.cs
using Microsoft.AspNetCore.Mvc;
using PizzariaMVCAtivdade.Models;
using PizzariaMVCAtivdade.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PizzariaMVCAtivdade.Controllers
{
    public class SaborController : Controller
    {
        private PizzariaDbContext _context;

        public SaborController(PizzariaDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View(_context.Sabores);
        }
        public IActionResult Detalhes(int id) => View(_context.Sabores.Find(id));
        public IActionResult Criar() => View();

        [HttpPost]
        public IActionResult Criar(PostSaborDTO saborDto)
        {
            if (!ModelState.IsValid) return View(saborDto);
            Sabor s1 = new Sabor(saborDto.Nome,saborDto.FotoURL);
            _context.Add(s1);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        
        public IActionResult Atualizar(int id)
        {
            var result = _context.Sabores.FirstOrDefault(s => s.Id == id);
            return View(result);
        }

        [HttpPost,ActionName("Atualizar Sabor")]
        public IActionResult ConfirmarAtualizar(int id, PostSaborDTO saborDto)
        {
            var result = _context.Sabores.FirstOrDefault(s => s.Id == id);
            result.Atualizar(saborDto.Nome, saborDto.FotoURL);
            _context.Sabores.Update(result);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Deletar(int id)
        {
            var result = _context.Sabores.FirstOrDefault(s => s.Id == id);
            return View(result); ;
        }
        [HttpPost,ActionName("Deletar Sabor")]
        public IActionResult ConfirmarDeletar(int id)
        {
            var result = _context.Sabores.FirstOrDefault(s => s.Id == id);
            _context.Sabores.Remove(result);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

PizzariaMVCAtivdade/Controllers/TamanhoController.cs
using Microsoft.AspNetCore.Mvc;
using PizzariaMVCAtivdade.Models;
using PizzariaMVCAtivdade.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PizzariaMVCAtivdade.Controllers
{
    public class TamanhoController : Controller
    {
        private PizzariaDbContext _context;

        public TamanhoController(PizzariaDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View(_context.Tamanhos);
        }
        public IActionResult Criar() => View();

        [HttpPost]
        public IActionResult Criar(PostTamanhoDTO tamanhoDto)
        {
            Tamanho c1 = new(tamanhoDto.Nome);
            _context.Tamanhos.Add(c1);
            _context.SaveChanges(); ;
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Atualizar(int id)
        {
            var result = _context.Tamanhos.FirstOrDefault(s => s.Id == id);
            return View(result);
        }

        [HttpPost, ActionName("Atualizar Tamnho")]
        public IActionResult ConfirmarAtualizar(int id, PostTamanhoDTO tamanhoDto)
        {
            var result = _context.Tamanhos.FirstOrDefault(t => t.Id == id);
            result.Atualizar(tamanhoDto.Nome);
            _context.Tamanhos.Update(result);
            _context.SaveChanges(); ;
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Deletar(int id)
        {
            var result = _context.Tamanhos.FirstOrDefault(s => s.Id == id);
            return View(result);
        }
        [HttpPost, ActionName("Deletar Tamanho")]
        public IActionResult ConfirmarDeletar(int id)
        {
            var result = _context.Tamanhos.FirstOrDefault(t => t.Id == id);
            _context.Tamanhos.Remove(result);
            _context.SaveChanges(); ;
            return RedirectToAction(nameof(Index));
        }
    }
}

PizzariaMVCAtivdade/Views/Shared/_Btn_cadastrar.cshtml
@model string

<div class="row ">
    <a asp-action="Criar" class="btn btn-block btn-primary col-6 mx-auto">
        <i class="fa-solid fa-circle-plus"></i> Novo @Model
    </a>
</div>

PizzariaMVCAtivdade/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizzaria </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light badge-warning border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pizza" asp-action="Index">Pizzaria</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Index">Pizzas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sabor" asp-action="Index">Sabores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tamanho" asp-action="Index">Tamanhos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Pizzaria - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>